nameOverride: ""
fullnameOverride: ""

registry:
  enabled: true
  name: apicurio-registry

  app:
    replicas: 1

    ingress:
      enabled: false
      host: ""
      ingressClassName: nginx
      annotations:
        nginx.org/proxy-connect-timeout: "30s"

    auth:
      enabled: false
      appClientId: registry-client-api
      uiClientId: registry-client-ui
      authServerUrl: https://keycloak.example.com/realms/registry
      redirectUri: https://registry-ui.example.com
      logoutUrl: https://registry-ui.example.com

    env: []

    resources:
      requests:
        cpu: 0.5
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi

    podDisruptionBudget:
      enabled: false

  ui:
    enabled: true
    replicas: 1

    ingress:
      enabled: false
      host: ""
      ingressClassName: nginx
      annotations:
        nginx.org/proxy-connect-timeout: "30s"

    env: []

    podDisruptionBudget:
      enabled: false

  # docs: https://www.apicur.io/registry/docs/apicurio-registry/3.3.x/getting-started/assembly-deploying-registry-operator.html
  storage:
    # postgresql | mysql | kafkasql | gitops | kubernetesops
    type: gitops

    # GitOps storage (read-only). Schemas are managed via Git commits.
    # Example repo: https://github.com/Apicurio/apicurio-registry-gitops-example
    gitops:
      # only: pull | push
      mode: pull
      # Registry instance identifier.
      registryId: prod
      repos:
        - url: https://github.com/Apicurio/apicurio-registry-gitops-example.git
          branch: main # to manage prod
          dir: registry # workspace name clone

    # For pull mode (using private SSH repos)
    pull:
      sshKeys:
        name: gitops-ssh-keys
        key: id_ed25519
      knownHosts:
        name: gitops-known-hosts
        key: known_hosts

    # For push mode (CI git push over SSH on port 2222):
    push:
      authorizedKeys:
        name: gitops-authorized-keys
        key: authorized_keys
      hostKey:
        name: gitops-host-key
        key: ssh_host_key

    sql:
      dataSource:
        url: jdbc:postgresql://postgresql.my-project.svc:5432/registry
        username: registry_user
        password:
          name: postgresql-credentials
          key: password

    kafkasql:
      bootstrapServers: kafka-cluster-kafka-bootstrap.kafka.svc:9092
      tls:
        truststoreSecretRef:
          name: kafka-cluster-cluster-ca-cert
          key: ca.p12
        truststorePasswordSecretRef:
          name: kafka-cluster-cluster-ca-cert
          key: ca.password
      scram:
        secretName: registry
        secretKey: sasl.jaas.config

    kubernetesops:
      registryId: default
      namespace: ""
