nameOverride: ""
fullnameOverride: ""

registry:
  enabled: true
  name: apicurio-registry

  app:
    replicas: 1
    ingress:
      enabled: false
      host: ""

  ui:
    enabled: true
    ingress:
      enabled: false
      host: ""

  storage:
    type: kafkasql
    kafkasql:
      bootstrapServers: kafka-cluster-kafka-bootstrap.kafka.svc:9092
      tls:
        truststoreSecretRef:
          name: kafka-cluster-cluster-ca-cert
          key: ca.p12
        truststorePasswordSecretRef:
          name: kafka-cluster-cluster-ca-cert
          key: ca.password
      scram:
        secretName: registry
        secretKey: sasl.jaas.config

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi