apiVersion: v2
name: builder
appVersion: "0.30.0"
description: BuildKit daemon for internal CI/CD image builds
type: application
version: 0.1.0
kubeVersion: ">=1.30.0-0"
keywords:
  - builder
  - image
  - ci/cd
  - kubernetes
maintainers:
  - name: Truong Thanh Binh
    email: dev.binhtt@gmail.com
    url: https://github.com/BevisDev

