values:
- name: ID
  type: NUMBER(10)
  nullable: false
- name: ACCOUNT_TYPE
  type: VARCHAR2(32)
- name: ACCOUNT_NUMBER
  type: VARCHAR2(32)
- name: CURRENCY
  type: VARCHAR2(8)
- name: CUSTOMER_ID
  type: NUMBER(10)
- name: CONTRACT_ID
  type: NUMBER(10)
- name: STATUS
  type: VARCHAR2(16)
