apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "builder.fullname" . }}-config
  namespace: {{ include "builder.namespace" . }}
  labels:
    {{- include "builder.labels" . | nindent 4 }}
data:
  buildkitd.toml: |
    {{- if .Values.buildkit.debug }}
    debug = true
    {{- end }}
    [cdi]
      disabled = {{ .Values.buildkit.cdi.disabled }}
    {{- if and (not .Values.buildkit.cdi.disabled) .Values.buildkit.cdi.specDirs }}
      specDirs = [{{ range $i, $dir := .Values.buildkit.cdi.specDirs }}{{ if $i }}, {{ end }}"{{ $dir }}"{{ end }}]
    {{- end }}
    {{- if .Values.registry.host }}
    [registry."{{ .Values.registry.host }}"]
    {{- if .Values.registry.http }}
      http = true
    {{- end }}
    {{- if .Values.registry.insecure }}
      insecure = true
    {{- end }}
    {{- end }}
