apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "builder.fullname" . }}-config
  namespace: {{ include "builder.namespace" . }}
  labels:
    {{- include "builder.labels" . | nindent 4 }}
data:
  buildkitd.toml: |
    {{- if .Values.buildkit.debug }}
    debug = true
    {{- end }}
    {{- if .Values.registry.host }}
    [registry."{{ .Values.registry.host }}"]
    {{- if .Values.registry.http }}
      http = true
    {{- end }}
    {{- if .Values.registry.insecure }}
      insecure = true
    {{- end }}
    {{- end }}
