global:
  imageRegistry: quay.io
  imageRepository: dwh
  imagePullSecrets: []
    # - name: dockerhub-regcred
  imagePullPolicy: IfNotPresent
  imageTag: "3.3.0"

  images:
    operator:
      name: apicurio-registry-3-operator
      tag: ~

    app:
      name: apicurio-registry
      tag: ~

    ui:
      name: apicurio-registry-ui
      tag: ~

    gitops:
      name: apicurio-registry-gitops-sync
      tag: ~

operator:
  enabled: true

  operator:
    enabled: true
    replicas: 1
    watchNamespaces:
      - kafka
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 100Mi

registry:
  enabled: true

  registry:
    enabled: true
    name: apicurio-registry

    app:
      replicas: 2

      ingress:
        enabled: false
        host: ""
        ingressClassName: nginx
        annotations:
          nginx.org/proxy-connect-timeout: "30s"

      auth:
        enabled: false
        appClientId: registry-client-api
        uiClientId: registry-client-ui
        authServerUrl: https://keycloak.example.com/realms/registry
        redirectUri: https://registry-ui.example.com
        logoutUrl: https://registry-ui.example.com

      resources:
        requests:
          cpu: 0.5
          memory: 512Mi
        limits:
          cpu: 1
          memory: 1Gi

    ui:
      enabled: true
      replicas: 1
      ingress:
        enabled: false
        host: ""
        ingressClassName: nginx
        annotations:
          nginx.org/proxy-connect-timeout: "30s"

    storage:
      type: gitops
      gitops:
        mode: pull
        registryId: prod
        repos:
          - url: git@github.com:Apicurio/apicurio-registry-gitops-example.git
            branch: main
            dir: default
        pull:
          sshKeys:
            name: git-ssh # Secret name
            key: id_ed25519 # Key within the Secret (default: id_ed25519)
          knownHosts:
            name: git-known-hosts
            key: known_hosts
            