apiVersion: v1
appVersion: 19.1.1
description: GitLab Runner
keywords:
- git
- ci
- deploy
maintainers:
- name: Truong Thanh Binh
  email: dev.binhtt@gmail.com
  url: https://github.com/BevisDev
name: gitlab-runner
version: 0.90.1
