groupId: group1
schema: MAIN
topicPrefix: cdc.group1
source:
  type: debezium
  database: oracle
  signal: true
  heartbeat: true
  heartbeatPrefix: __heartbeat.uat
tables:
  - name: TABLE1
    description: CDC for MAIN.TABLE1
    key:
      description: CDC Key for MAIN.TABLE1
      versions:
        - version: "1"
          state: ENABLED
          description: CDC Key for MAIN.TABLE1 v1
    value:
      description: CDC Value for MAIN.TABLE1
      versions:
        - version: "1"
          state: ENABLED
          description: CDC Value for MAIN.TABLE1 v1

  - name: TABLE2
    description: CDC for MAIN.TABLE2
    key:
      description: CDC Key for MAIN.TABLE2
      versions:
        - version: "1"
          state: ENABLED
          description: CDC Key for MAIN.TABLE2 v1
    value:
      description: CDC Value for MAIN.TABLE2
      versions:
        - version: "1"
          state: ENABLED
          description: CDC Value for MAIN.TABLE2 v1
