apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: {{ include "kafka.clusterName" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.kafka.metadata.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  kafka:
    version: {{ .Values.kafka.version | quote }}
    metadataVersion: {{ .Values.kafka.version | quote }}
    listeners:
      {{- toYaml .Values.kafka.listeners | nindent 6 }}
    config:
      {{- toYaml .Values.kafka.config | nindent 6 }}
    {{- with .Values.kafka.jvmOptions }}
    jvmOptions:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.kafka.logging }}
    logging:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if .Values.kafka.template }}
    template:
      {{- toYaml .Values.kafka.template | nindent 6 }}
    {{- end }}
  {{- if .Values.entityOperator.enabled }}
  entityOperator:
    {{- if .Values.entityOperator.topicOperator }}
    topicOperator:
      {{- toYaml .Values.entityOperator.topicOperator | nindent 6 }}
    {{- else }}
    topicOperator: {}
    {{- end }}
    {{- if .Values.entityOperator.userOperator }}
    userOperator:
      {{- toYaml .Values.entityOperator.userOperator | nindent 6 }}
    {{- else }}
    userOperator: {}
    {{- end }}
  {{- end }}
  {{- if .Values.kafkaExporter.enabled }}
  kafkaExporter:
    {{- if .Values.kafkaExporter.spec }}
    {{- toYaml .Values.kafkaExporter.spec | nindent 4 }}
    {{- else }}
    {}
    {{- end }}
  {{- end }}
  {{- if .Values.cruiseControl.enabled }}
  cruiseControl:
    {{- if .Values.cruiseControl.spec }}
    {{- toYaml .Values.cruiseControl.spec | nindent 4 }}
    {{- else }}
    {}
    {{- end }}
  {{- end }}
