apiVersion: v2
appVersion: 3.3.0
description: Apicurio Operator
keywords:
- apicurio
- schema-registry
- operator
maintainers:
  - name: Truong Thanh Binh
    email: dev.binhtt@gmail.com
    url: https://github.com/BevisDev
name: apicurio-operator
version: 0.1.0
