FROM apache/airflow:3.3.1

RUN pip install --no-cache-dir \
    "apache-airflow==3.3.1" \
    airflow-clickhouse-plugin==1.8.0 \
    apache-airflow-providers-oracle==4.6.3 \
    apache-airflow-providers-microsoft-mssql==4.7.1 \
    airflow-plugin-watchdog==0.6.4