{{- range .Values.tlsRoutes }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default $.Release.Namespace }}
  labels:
    {{- include "gw.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- include "gw.parentRefs" (dict "route" . "root" $) | nindent 4 }}
  {{- with .hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- include "gw.tlsRouteRules" . | nindent 4 }}
{{- end }}
