apiVersion: v2
appVersion: 3.3.0
description: Schema Registry Chart
keywords:
- apicurio
- schema-registry
maintainers:
  - name: Truong Thanh Binh
    email: dev.binhtt@gmail.com
    url: https://github.com/BevisDev
name: schema-registry
version: 0.1.0
dependencies:
  - name: apicurio-operator
    condition: apicurio-operator.enabled
    repository: file://./charts/apicurio-operator
    version: 0.1.0
  - name: apicurio-registry
    condition: apicurio-registry.enabled
    repository: file://./charts/apicurio-registry
    version: 0.1.0
