global:
  imageRegistry: quay.io
  imageRepository: dwh
  imagePullSecrets: []
    # - name: dockerhub-regcred
  imagePullPolicy: IfNotPresent
  imageTag: "3.3.0"

  images:
    operator:
      name: apicurio-registry-3-operator
      tag: ~

    app:
      name: apicurio-registry
      tag: ~

    ui:  
      name: apicurio-registry-ui
      tag: ~

    gitops:
      name: apicurio-registry-gitops-sync
      tag: ~
  
operator:
  enabled: true

  operator:
    enabled: true

    replicas: 1

    watchNamespaces:
      - kafka

    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 100Mi

registry:
  enabled: true
  
  registry:
    name: apicurio-registry
    storage:
      type: kafkasql
      kafkasql:
        bootstrapServers: dp-kafka-kafka-bootstrap.kafka.svc:9092
        tls:
          truststoreSecretRef:
            name: dp-kafka-cluster-ca-cert
            key: ca.p12
          truststorePasswordSecretRef:
            name: dp-kafka-cluster-ca-cert
            key: ca.password
        scram:
          secretName: registry
          secretKey: sasl.jaas.config

    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
