{{- if .Values.registry.enabled }}
apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry3
metadata:
  name: {{ .Values.registry.name }}
  namespace: {{ .Release.Namespace }}
spec:
  app:
    replicas: {{ .Values.registry.app.replicas }}
    storage:
      type: {{ .Values.registry.storage.type }}
      {{- if .Values.registry.storage.sql }}
      sql:
        {{- toYaml .Values.registry.storage.sql | nindent 8 }}
      {{- else if .Values.registry.storage.kafkasql }}
      kafkasql:
        {{- toYaml .Values.registry.storage.kafkasql | nindent 8 }}
      {{- end }}
    {{- with .Values.registry.app.env }}
    env:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if .Values.registry.app.ingress.enabled }}
    ingress:
      enabled: true
      host: {{ .Values.registry.app.ingress.host }}
    {{- else }}
    ingress:
      enabled: false
    {{- end }}
    podTemplateSpec:
      spec:
        {{- if .Values.registry.resources }}
        containers:
          - name: {{ .Values.registry.name }}-app
            resources:
              {{- toYaml .Values.registry.resources | nindent 14 }}
        {{- end }}
        {{- with .Values.registry.app.affinity }}
        affinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
  ui:
    enabled: {{ .Values.registry.ui.enabled }}
    replicas: {{ .Values.registry.ui.replicas }}
    {{- if .Values.registry.ui.ingress.enabled }}
    ingress:
      enabled: true
      host: {{ .Values.registry.ui.ingress.host }}
    {{- else }}
    ingress:
      enabled: false
    {{- end }}
{{- end }}